USE QUANLYNHAKHOA
GO
INSERT INTO Thuoc (TenThuoc, XuatXu, CongDung) VALUES 
(N'Metoclopramide', N'Hàn Quốc', N'Chống nôn và buồn nôn'),
(N'Naproxen', N'Tây Ban Nha', N'Chống viêm, giảm đau'),
(N'Olanzapine', N'Việt Nam', N'Điều trị tâm thần phân liệt'),
(N'Olmesartan', N'Pháp', N'Điều trị tăng huyết áp'),
(N'Ondansetron', N'Mỹ', N'Chống nôn và buồn nôn'),
(N'Orphenadrine', N'Thụy Điển', N'Giảm đau cơ, chống co giật'),
(N'Oxcarbazepine', N'Hàn Quốc', N'Điều trị đau thần kinh'),
(N'Pantoprazole', N'Tây Ban Nha', N'Giảm axit dạ dày'),
(N'Paroxetine', N'Việt Nam', N'Điều trị trầm cảm'),
(N'Phenazopyridine', N'Anh', N'Giảm đau và kích thích tiểu đường'),
(N'Phenytoin', N'Bỉ', N'Điều trị co giật'),
(N'Pregabalin', N'Canada', N'Điều trị đau thần kinh'),
(N'Prochlorperazine', N'Hàn Quốc', N'Chống nôn và buồn nôn'),
(N'Quetiapine', N'Bỉ', N'Điều trị tâm thần phân liệt'),
(N'Ranitidine', N'Canada', N'Giảm axit dạ dày'),
(N'Rosuvastatin', N'Tây Ban Nha', N'Giảm cholesterol'),
(N'Sertraline', N'Thụy Sĩ', N'Điều trị trầm cảm'),
(N'Simvastatin', N'Việt Nam', N'Giảm cholesterol'),
(N'Spironolactone', N'Mỹ', N'Điều trị tăng huyết áp'),
(N'Sumatriptan', N'Đức', N'Điều trị đau nửa đầu'),
(N'Tamsulosin', N'Anh', N'Giảm triệu chứng tiểu đường'),
(N'Telmisartan', N'Canada', N'Điều trị tăng huyết áp'),
(N'Trazodone', N'Tây Ban Nha', N'Điều trị rối loạn ngủ'),
(N'Valsartan', N'Pháp', N'Điều trị tăng huyết áp'),
(N'Venlafaxine', N'Hàn Quốc', N'Điều trị trầm cảm'),
(N'Zolpidem', N'Việt Nam', N'Điều trị mất ngủ'),
(N'Zolmitriptan', N'Anh', N'Điều trị đau nửa đầu'),
(N'Cephalexin', N'Đức', N'Kháng sinh trị nhiễm khuẩn'),
(N'Cetirizine', N'Thụy Điển', N'Chống dị ứng'),
(N'Clopidogrel', N'Hàn Quốc', N'Chống đông máu'),
(N'Clotrimazole', N'Tây Ban Nha', N'Chống nấm nướu, nấm da'),
(N'Clindamycin', N'Mỹ', N'Kháng sinh trị nhiễm khuẩn'),
(N'Cyclobenzaprine', N'Bỉ', N'Giảm đau cơ, chống co giật'),
(N'Desloratadine', N'Canada', N'Chống dị ứng'),
(N'Dexamethasone', N'Việt Nam', N'Chống viêm, chống dị ứng'),
(N'Diazepam', N'Pháp', N'An thần, chống co giật'),
(N'Duloxetine', N'Anh', N'Điều trị trầm cảm'),
(N'Esomeprazole', N'Thụy Điển', N'Giảm axit dạ dày'),
(N'Fexofenadine', N'Hàn Quốc', N'Chống dị ứng'),
(N'Fluconazole', N'Việt Nam', N'Chống nấm nướu, nấm da'),
(N'Fluticasone', N'Mỹ', N'Dùng trong điều trị hen suyễn'),
(N'Furosemide', N'Tây Ban Nha', N'Lợi tiểu, giảm chất lưu'),
(N'Gabapentin', N'Bỉ', N'Điều trị đau thần kinh'),
(N'Hydrochlorothiazide', N'Canada', N'Giảm huyết áp, lợi tiểu'),
(N'Hydroxyzine', N'Pháp', N'An thần, chống dị ứng'),
(N'Ibuprofen', N'Hàn Quốc', N'Chống viêm, giảm đau'),
(N'Imipramine', N'Anh', N'Điều trị trầm cảm'),
(N'Isosorbide', N'Đức', N'Giãn cơ và làm dễ chịu tim'),
(N'Ketorolac', N'Tây Ban Nha', N'Giảm đau mạnh'),
(N'Lamotrigine', N'Việt Nam', N'Điều trị đau thần kinh'),
(N'Lansoprazole', N'Thụy Sĩ', N'Giảm axit dạ dày'),
(N'Levofloxacin', N'Mỹ', N'Kháng sinh trị nhiễm khuẩn'),
(N'Lorazepam', N'Pháp', N'An thần, giảm căng thẳng'),
(N'Losartan HCTZ', N'Anh', N'Điều trị tăng huyết áp'),
(N'Melatonin', N'Bỉ', N'Hỗ trợ điều trị rối loạn giấc ngủ'),
(N'Methylprednisolone', N'Canada', N'Chống viêm, chống dị ứng'),
(N'Metformin', N'Bỉ', N'Điều trị đái tháo đường'),
(N'Methotrexate', N'Canada', N'Điều trị ung thư'),
(N'Metoprolol', N'Hàn Quốc', N'Giảm huyết áp, chống tim đập nhanh');

INSERT INTO Thuoc (TenThuoc, XuatXu, CongDung) VALUES 
(N'Aspirin', N'Đức', N'Giảm đau, hạ sốt'),
(N'Ibuprofen', N'Mỹ', N'Chống viêm, giảm đau'),
(N'Acetaminophen', N'Canada', N'Giảm đau, hạ sốt'),
(N'Amoxicillin', N'Anh', N'Kháng sinh trị nhiễm khuẩn'),
(N'Cephalexin', N'Trung Quốc', N'Kháng sinh trị nhiễm khuẩn'),
(N'Diphenhydramine', N'Thụy Điển', N'An thần, chống dị ứng'),
(N'Loratadine', N'Pháp', N'Chống dị ứng'),
(N'Omeprazole', N'Mỹ', N'Giảm axit dạ dày'),
(N'Ranitidine', N'Đức', N'Giảm axit dạ dày'),
(N'Fluoxetine', N'Canada', N'Điều trị trầm cảm'),
(N'Lisinopril', N'Trung Quốc', N'Điều trị tăng huyết áp'),
(N'Sertraline', N'Thụy Sĩ', N'Điều trị trầm cảm'),
(N'Metformin', N'Pháp', N'Điều trị đái tháo đường'),
(N'Simvastatin', N'Mỹ', N'Giảm cholesterol'),
(N'Alprazolam', N'Anh', N'An thần, giảm căng thẳng'),
(N'Warfarin', N'Trung Quốc', N'Chống đông máu'),
(N'Prednisone', N'Pháp', N'Chống viêm, chống dị ứng'),
(N'Metoprolol', N'Mỹ', N'Giảm huyết áp, chống tim đập nhanh'),
(N'Levothyroxine', N'Đức', N'Điều trị rối loạn tuyến giáp'),
(N'Hydrochlorothiazide', N'Canada', N'Giảm huyết áp, lợi tiểu');


INSERT INTO Thuoc (TenThuoc, XuatXu, CongDung) VALUES 
(N'Amoxicillin', N'Anh', N'Kháng sinh trị nhiễm khuẩn trong điều trị nha khoa'),
(N'Chlorhexidine', N'Pháp', N'Chống nhiễm trùng răng và nướu'),
(N'Ibuprofen', N'Mỹ', N'Chống viêm, giảm đau sau phẫu thuật nha khoa'),
(N'Lidocaine', N'Canada', N'Gel tê cho phẫu thuật nha khoa'),
(N'Fluoride Gel', N'Trung Quốc', N'Bảo vệ men răng, ngăn chặn sâu răng'),
(N'Hydrogen Peroxide', N'Hàn Quốc', N'Chất tẩy trắng răng'),
(N'Dexamethasone', N'Pháp', N'Giảm viêm và đau sau phẫu thuật nha khoa'),
(N'Chlorpheniramine', N'Thụy Điển', N'Chống dị ứng sau phẫu thuật nha khoa'),
(N'Oral Rinse', N'Anh', N'Dung dịch súc miệng nha khoa'),
(N'Saline Solution', N'Mỹ', N'Dung dịch muối sinh lý cho hỗ trợ trong phẫu thuật nha khoa'),
(N'Eugenol', N'Pháp', N'Chất làm nguội và chống đau trong điều trị nha khoa'),
(N'Tetracaine', N'Đức', N'Gel tê cho phẫu thuật nha khoa'),
(N'Metronidazole', N'Canada', N'Kháng sinh cho điều trị nhiễm trùng nướu'),
(N'Calcium Hydroxide', N'Trung Quốc', N'Chất làm sạch và kháng khuẩn trong điều trị nha khoa'),
(N'Articaine', N'Hàn Quốc', N'Chất tê nhanh và hiệu quả trong phẫu thuật nha khoa'),
(N'Clindamycin', N'Bỉ', N'Kháng sinh cho điều trị nhiễm trùng nướu'),
(N'Epinephrine', N'Pháp', N'Chất kích thích tim để kiểm soát chảy máu trong phẫu thuật nha khoa'),
(N'Acetaminophen', N'Mỹ', N'Giảm đau sau phẫu thuật nha khoa'),
(N'Silver Diamine Fluoride', N'Anh', N'Chất chống sâu răng và nhiễm trùng nướu'),
(N'Chlorpromazine', N'Trung Quốc', N'Giảm căng thẳng và lo lắng trước và sau phẫu thuật nha khoa'),
(N'Amlexanox', N'Hàn Quốc', N'Chất chống viêm và chống dị ứng trong điều trị nha khoa');
